print("This is line 1")
print("This is line 2")
print("This is line 3")
print("This is line 4")
print("This is line 5")
print("This is line 6")
print("This is line 7")
print("This is line 8")
print("This is line 9")
print("This is line 10")

